# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrenciasHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(default=datetime.datetime(2020, 3, 1, 18, 50, 51, 578487, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430')),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u041a\u0443\u0440\u0441 \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u041a\u0443\u0440\u0441 \u043f\u043e\u043a\u0443\u043f\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u041a\u0443\u0440\u0441 \u0432\u0430\u043b\u044e\u0442\u044b',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b \u0432\u0430\u043b\u044e\u0442',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0432\u0430\u043b\u044e\u0442\u044b')),
                ('short_name', models.CharField(max_length=4, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u043b\u044e\u0442\u0430',
                'verbose_name_plural': '\u0412\u0430\u043b\u044e\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='currenciashistory',
            name='curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.Currencies', verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
    ]
