# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenciashistory',
            name='period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
