# Generated by Django 3.0.3 on 2020-03-02 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20200301_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currenciashistory',
            options={'ordering': ['period'], 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterField(
            model_name='currenciashistory',
            name='period',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
