# Generated by Django 3.0.3 on 2020-03-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20200302_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrenciasHistory',
            new_name='CurrenciesHistory',
        ),
    ]
